version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module-with-firefox:
    image: srikp/selenium-docker
    depends_on: 
      - chrome
      - firefox
    environment: 
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=search-module.xml
    volumes: 
      - ./search-result:/usr/share/udemy/test-output
  book-flight-module-with-chrome:
    image: srikp/selenium-docker
    depends_on: 
      - chrome
      - firefox
    environment: 
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=book-flight-module.xml
    volumes: 
      - ./book-flight-result:/usr/share/udemy/test-output